### ISSUE TITLE
Error: Cannot find module 'folktale/Maybe'

### ISSUE THREAD

**Issue by farzadhallaji** [wavesplatform/data-service#157]
i follow read.me file and get this error :
```
root@:~/data-service# npm install 
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7

root@:~/data-service# export $(cat variables.env | xargs) &&
 NODE_ENV=production node src/index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'folktale/Maybe'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/data-service/src/utils/db/index.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by dvshur** [comment]
Do you use `develop` or `master` branch? Master should be stable, while develop is not guaranteed to be.

`folktale/Maybe` error is a bug sometimes introduced while developing on Mac OS: paths are case-insensitive, but in Linux they're case-sensitive. Sorry about that, will fix shortly.

**Comment by dvshur** [comment]
Should be fixed now, closing.
